# Generated by Django 4.2.13 on 2024-07-09 15:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateField(auto_now_add=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=50, region="UA"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("pending", "pending"),
                            ("completed", "completed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
