# Generated by Django 4.2.13 on 2024-07-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        ("adoption", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="cat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pets.catprofile"),
        ),
    ]
