# Generated by Django 4.2.13 on 2024-07-09 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="catprofile",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked_cats", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="catphoto",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="pets.catprofile",
            ),
        ),
    ]
