version: '3.8'

services:
  frontend:
    container_name: frontend-nginx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROJECT_DIR=/src
      - ENVIRON=dev
    ports:
      - "8080:80"